version: "3.8"

services:
  karin:
    image: karinjs/karin:latest
    container_name: karin
    restart: unless-stopped
    network_mode: "bridge"
    ports:
      - "7777:7777"
    environment:
      - PLUGIN_LIST="@karinjs/plugin-basic"
    volumes:
      - /opt/karin/@karinjs:/app/@karinjs
      - /opt/karin/plugins:/app/plugins
