name: Build Docker

on:
  workflow_call:

env:
  DOCKERHUB_REPO: karinjs/karin
  GHCR_REPO: ghcr.io/karinjs/karin

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            os: ubuntu-latest
          - platform: linux/arm64
            os: ubuntu-24.04-arm
    steps:
      - name: 检出代码
        uses: actions/checkout@v6

      - name: 设置 Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: 登录GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          push: true
          platforms: ${{ matrix.platform }}
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{ matrix.platform == 'linux/amd64' && 'amd64' || 'arm64' }}
            ${{ env.GHCR_REPO }}:${{ matrix.platform == 'linux/amd64' && 'amd64' || 'arm64' }}

  push:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: 设置 Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: 登录GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 创建并推送多平台清单
        run: |
          docker buildx imagetools create \
            -t ${{ env.DOCKERHUB_REPO }}:latest \
            ${{ env.DOCKERHUB_REPO }}:amd64 \
            ${{ env.DOCKERHUB_REPO }}:arm64

          docker buildx imagetools create \
            -t ${{ env.GHCR_REPO }}:latest \
            ${{ env.GHCR_REPO }}:amd64 \
            ${{ env.GHCR_REPO }}:arm64

      - name: 检查镜像
        run: |
          docker buildx imagetools inspect ${{ env.DOCKERHUB_REPO }}:latest
          docker buildx imagetools inspect ${{ env.GHCR_REPO }}:latest